export const ROLES = {
  OWNER: 'OWNER',
  FRONT_DESK: 'FRONT_DESK',
  BAR_STAFF: 'BAR_STAFF',
  KITCHEN: 'KITCHEN',
  SHOP_STAFF: 'SHOP_STAFF',
  MEMBER: 'MEMBER',
};

export const ROLE_HIERARCHY = {
  OWNER: ['OWNER', 'FRONT_DESK', 'BAR_STAFF', 'KITCHEN', 'SHOP_STAFF', 'MEMBER'],
  FRONT_DESK: ['FRONT_DESK', 'MEMBER'],
  BAR_STAFF: ['BAR_STAFF', 'KITCHEN'],
  SHOP_STAFF: ['SHOP_STAFF'],
  KITCHEN: ['KITCHEN'],
  MEMBER: ['MEMBER'],
};
