export const BOOKING_STATUS = {
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
};

export const BOOKING_TYPE = {
  NORMAL: 'NORMAL',
  SOCIAL: 'SOCIAL',
};

export const MEMBER_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  SUSPENDED: 'SUSPENDED',
};

export const ORDER_CHANNEL = {
  COUNTER: 'COUNTER',
  ONLINE: 'ONLINE',
  BAR: 'BAR',
};

export const ORDER_STATUS = {
  PLACED: 'PLACED',
  PREPARING: 'PREPARING',
  SERVED: 'SERVED',
  PACKED: 'PACKED',
  READY: 'READY',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const FULFILMENT_TYPE = {
  DINE_IN: 'DINE_IN',
  PICKUP: 'PICKUP',
  DELIVERY: 'DELIVERY',
};

export const PAYMENT_MODE = {
  CASH: 'CASH',
  CARD: 'CARD',
  UPI: 'UPI',
  ONLINE: 'ONLINE',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
};

export const PRODUCT_CATEGORY = {
  RACKETS: 'RACKETS',
  BALLS: 'BALLS',
  SHOES: 'SHOES',
  ACCESSORIES: 'ACCESSORIES',
  APPAREL: 'APPAREL',
};

export const MENU_CATEGORY = {
  BEVERAGES: 'BEVERAGES',
  SNACKS: 'SNACKS',
  MEALS: 'MEALS',
  DESSERTS: 'DESSERTS',
  HEALTH_DRINKS: 'HEALTH_DRINKS',
};

export const TABLE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
};

export const TAB_STATUS = {
  OPEN: 'OPEN',
  SETTLED: 'SETTLED',
};

export const SHIFT_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
};

export const TRANSACTION_SOURCE = {
  COURT: 'COURT',
  SHOP: 'SHOP',
  BAR: 'BAR',
  MEMBERSHIP: 'MEMBERSHIP',
  OTHER: 'OTHER',
};

export const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED',
};

export const INVOICE_TYPE = {
  MEMBERSHIP: 'MEMBERSHIP',
  BUSINESS: 'BUSINESS',
};

export const EXPENSE_STATUS = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
};

export const LEAD_STAGE = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUOTED: 'QUOTED',
  WON: 'WON',
  LOST: 'LOST',
};

export const QUOTATION_STATUS = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
};

export const LEAVE_TYPE = {
  CASUAL: 'CASUAL',
  SICK: 'SICK',
  PAID: 'PAID',
  UNPAID: 'UNPAID',
};

export const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const PAYROLL_STATUS = {
  DRAFT: 'DRAFT',
  PROCESSED: 'PROCESSED',
  PAID: 'PAID',
};

export const INQUIRY_SOURCE = {
  WALK_IN: 'WALK_IN',
  PHONE_CALL: 'PHONE_CALL',
  INQUIRY_FORM: 'INQUIRY_FORM',
  REFERRAL: 'REFERRAL',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  OTHER: 'OTHER',
};
